Build refinements - fixed errors

diff --git a/cpp/test b/cpp/test
--- a/cpp/test
+++ b/cpp/test
@@ -3,6 +3,18 @@
 dir=$PWD
 cd ~/code/my_stl/cpp/build/ninja
 cmake -GNinja ../..
+if (( $? != 0 )); then
+    echo "Error with CMake"
+    cd $dir
+    return 1
+fi
+
 ninja
+if (( $? != 0 )); then
+    echo "Error with ninja"
+    cd $dir
+    return 2
+fi
+
 ./unit_tests
 cd $dir
